#!/usr/bin/bash

set -e

DOCDIR=docs
SCALADOC_DIR=$DOCDIR/scaladoc
SRCDIR=src
BINDIR=bin

echo "Generating scaladocs in: " $SCALADOC_DIR
if [ ! -d $SCALADOC_DIR ]; then
   mkdir $SCALADOC_DIR
fi
scaladoc `find $SRCDIR -name '*.scala'` -d $SCALADOC_DIR

echo "Building src, outputting to " $BINDIR
scalac -d $BINDIR `find src -name '*.scala'`